### ISSUE TITLE
mimic expects react-dom as 'ReactDOM' in page where import line resides.

### ISSUE THREAD

**Issue by gibbitz** [500tech/mimic#245]
It looks like 
`import 'mimic';`
fires code that requires all of react-dom as `ReactDOM` to be imported as:
`import * as ReactDOM from 'react-dom'`
using
`import {render} from 'react-dom'`
didn't work. I'd like to keep this as unobtrusive to my builds as possible and though I can work around this, wouldn't it be possible to import this class internally? it's one thing for mimic to require react it's another for it to require my app to require react. I'm using react on this project, but on other vanilla projects this would be annoying. Just sayin'...

BTW. I figured this out from watching the presentation you guys gave at nycnode(http://nycnode.com/videos/ilya-gelman-the-thorny-road-to-seamless-mocks) because I couldn't find a simple working example. You may want to add a simple example here: https://mimic.js.org/guides/ to help us common folk get up and running. I know this is really two bugs, but hey, I'm lazy. 

Awesome tool. Keep it coming!

**Comment by morsdyce** [comment]
Hi @gibbitz 

Mimic is meant to be used as a dev dependency and it should not reach your production builds.
To do this your build system should only include Mimic when running in development mode.

If you are using webpack you can define an environment flag which can tell your application in what environment it is running currently.

This is usually done using the [webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/) and should look like something like this:
```js
plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
    })
```

Then in your application you can use that flag to conditionally require Mimic
```js
if (process.env.NODE_ENV === 'development') {
 require('mimic')
}
```

We don't restrict this by default (stopping mimic from loading when we detect production environments) because that's a decision we feel we can't make for the end user.

There are use cases where you want your application to run in production mode, but still have mimic running in the background, for example running your application for marketing purposes with fake data.

I'll make sure we add an example for this and that we better explain that mimic should be loaded in development environments.

Thanks!

**Comment by gibbitz** [comment]
I'm not using webpack and this isn't in my production build, but the rest of my code is. I have a separate gulp task that uses a wrapper for my main app entry point where I ended up adding the dependency. What I wanted to do is just add it to my browserify bundler entries for my dev builds (which I can't do now due to the dependency -- thus the wrapper file). That said, why not make mimic self contained if this is the only dependency needed in my page for it to work? 

Even using webpack, wouldn't I need to write my page dependencies to include the whole class when all I'm using is `render()`? Not entirely because of worries about dead code (rollup/webpack have that covered) but for legibility ('what do I know about this code purely from the import statements?'). I didn't test what happens when I call `ReactDOM` 'reactDOM' or `RD` or whatever within my file, but it seems like this would also cause mimic to break. Why rely on user namespacing instead of importing ReactDOM yourselves?

**Comment by morsdyce** [comment]
Oh sorry about that, I assumed you wanted to remove mimic from production
builds.

We don't require anything on the user app, we bundle everything with 0
external dependencies. So it should not require react in your application
code.

I haven't tried running mimic on browesrify but it should work as it's just
a single bundled file that should not ask for external dependencies
I'll reach a computer soon and try to understand what exactly is the issue.

If you have some more details on what I need to look at to fully understand
the issue please let me know





On May 24, 2017 9:29 PM, "Paul Fox" <notifications@github.com> wrote:

I'm not using webpack and this isn't in my production build, but the rest
of my code is. I have a separate gulp task that uses a wrapper for my main
app entry point where I ended up adding the dependency. What I wanted to do
is just add it to my browserify bundler entries for my dev builds (which I
can't do now due to the dependency -- thus the wrapper file). That said,
why not make mimic self contained if this is the only dependency needed in
my page for it to work?

Even using webpack, wouldn't I need to write my page dependencies to
include the whole class when all I'm using is render()? Not entirely
because of worries about dead code (rollup/webpack have that covered) but
for legibility ('what do I know about this code purely from the import
statements?'). I didn't test what happens when I call ReactDOM 'reactDOM'
or RD or whatever within my file, but it seems like this would also cause
mimic to break. Why rely on user namespacing instead of importing ReactDOM
yourselves?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/500tech/mimic/issues/245#issuecomment-303811444>, or mute
the thread

**Comment by morsdyce** [comment]
Hey @gibbitz 

I downloaded a react browserify gulp boilerplate and installed mimic.
Tried importing ReactDom both as default import and render as a named import and it seems to be working.

You can clone the repo here and try it out:
https://github.com/morsdyce/mimic-browserify-example

It looks fine to me, could you look to see if this repo works for you?
If it does and still does not work in your project could you submit a small build process that creates the issue?

If it's hard to reproduce let me know and we could schedule a call over hangouts or skype to see if I can help you solve this issue.

**Comment by gibbitz** [comment]
Okay, so I'm not sure what's going on in my file that's making this happen, but removing react from the project, simplifying browsersync (removing proxying) and stripping it down to just mimic works fine. If I find the culprit with my complicated build, I'll report it here for posterity, but this one looks like a false alarm. Sorry to waste your time.

**Comment by morsdyce** [comment]
Ok let me know if you come up with something, thanks for investing your time to help Mimic be better!
