### ISSUE TITLE
Apply mocks once they are loaded

### ISSUE THREAD

**Issue by alexandrudanpop** [500tech/mimic#259]
Is there a possibility to apply mocks once they are loaded from the File System?

Right now I need to manually click Apply from the mimic interface for each request..

**Comment by morsdyce** [comment]
Hi Alex,

Once you load mimic mocks from the import api they are already active and
ready for use unless they were turned off when exported. You can check if
they are enabled by default by checking the mocks in the file system to
have active:true property.

There is no need for an apply button.

Could you share how you import these mocks?

Thanks

**Comment by alexandrudanpop** [comment]
Hi Maayan,

Turns out I had to clear local storage, and then they worked fine. Also if not valid JSON it will not work, but I think that is expected.

Thanks a lot for the quick response, this tool is really great.

**Comment by alexandrudanpop** [comment]
What was a little bit confusing for me was when I looked at the log and wanted to mock a GET request, I clicked on the request and created a mock (but at this point I didn't explicitly tell it that it was JSON from the UI). Then added it to a new group. 

When exporting the group and importing it to my project, I was missing the headers part from the JSON: 
       "headers": {
        "accept": "application/json, text/plain, */*"
      },

And without it didn't seem to auto mock the request.

Would be nice if by default JSON would be selected when creating a new mock. My JSON was just a string: "mocking !!!!"

**Comment by morsdyce** [comment]
Yeah, I get that. I thought about making JSON the default and decided that if I don't understand from the request that it should return JSON it would default to text.

This was mainly decided because when you have invalid JSON the request wouldn't work and the user wouldn't understand why.

I plan to add JSON validation to the editor which will allow me to safely select JSON as the default response type.

Thanks allot for the feedback!
