### ISSUE TITLE
Remote server black screen

### ISSUE THREAD

**Issue by sagivf** [500tech/mimic#267]
https://mimic.js.org/guides/remote.html

Tried following the instructions but I just get a white screen  with no errors on localhost:5000 (chrome, incognito doesn't help)

**Comment by morsdyce** [comment]
If you have a white screen it's probably loaded. However because mimic is by default closed it's very hard to see currently. 

Look at the bottom left corner of the page. I'll work on making it expanded by default when running in remote mode.

![image](https://user-images.githubusercontent.com/1665570/53959350-16c54f80-40ec-11e9-93d6-45d9ad3c86c4.png)

**Comment by sagivf** [comment]
Your right, it's ok. missed that :)

Great feature. Thanks!
